package com.KMOD.Main;

import com.KMOD.Blocks.BlockBlueFruit;
import com.KMOD.Blocks.BlockEnergyConverter;
import com.KMOD.Blocks.BlockEnergyEnchanter;
import com.KMOD.Blocks.BlockGiftsBlock;
import com.KMOD.Blocks.BlockHealingFlower;
import com.KMOD.Blocks.BlockHemp;
import com.KMOD.Blocks.BlockKetherBlock;
import com.KMOD.Blocks.BlockKetherCloud;
import com.KMOD.Blocks.BlockKetherCrystals;
import com.KMOD.Blocks.BlockKetherDirt;
import com.KMOD.Blocks.BlockKetherFlower;
import com.KMOD.Blocks.BlockKetherGemBlock;
import com.KMOD.Blocks.BlockKetherGlowingGrass;
import com.KMOD.Blocks.BlockKetherGrass;
import com.KMOD.Blocks.BlockKetherLeaves;
import com.KMOD.Blocks.BlockKetherLog;
import com.KMOD.Blocks.BlockKetherMagicFlower;
import com.KMOD.Blocks.BlockKetherMycena;
import com.KMOD.Blocks.BlockKetherOre;
import com.KMOD.Blocks.BlockKetherPillar;
import com.KMOD.Blocks.BlockKetherPlanks;
import com.KMOD.Blocks.BlockKetherPortal;
import com.KMOD.Blocks.BlockKetherRose;
import com.KMOD.Blocks.BlockKetherSapling;
import com.KMOD.Blocks.BlockKetherStone;
import com.KMOD.Blocks.BlockKetherTallGrass;
import com.KMOD.Blocks.BlockLifeLeaves;
import com.KMOD.Blocks.BlockMagicFruit;
import com.KMOD.Blocks.BlockMagicStone;
import com.KMOD.Blocks.BlockMovingSands;
import com.KMOD.Blocks.BlockUnbreakableKetherLeaves;
import com.KMOD.Blocks.BlockUnbreakableKetherLog;
import com.KMOD.DimensionBases.BiomeGenBaseKether;
import com.KMOD.DimensionBases.WorldProviderKether;
import com.KMOD.Events.EventGuiHandler;
import com.KMOD.Events.EventWorldGenKether;
import com.KMOD.Events.EventWorldGenMagicStoneOnly;
import com.KMOD.Items.ItemBlueFruit;
import com.KMOD.Items.ItemCottonCandy;
import com.KMOD.Items.ItemEnergyCrystal;
import com.KMOD.Items.ItemGravityWand;
import com.KMOD.Items.ItemJoint;
import com.KMOD.Items.ItemKether;
import com.KMOD.Items.ItemKetherArmor;
import com.KMOD.Items.ItemKetherAxe;
import com.KMOD.Items.ItemKetherHoe;
import com.KMOD.Items.ItemKetherLighter;
import com.KMOD.Items.ItemKetherPickaxe;
import com.KMOD.Items.ItemKetherShovel;
import com.KMOD.Items.ItemKetherSword;
import com.KMOD.Items.ItemKetherWand;
import com.KMOD.Items.ItemLegendaryMagicWand;
import com.KMOD.Items.ItemMagicFruit;
import com.KMOD.Recipes.RecipesKetherArmor;
import com.KMOD.Recipes.RecipesKetherGemBlocks;
import com.KMOD.Recipes.RecipesKetherTools;
import com.KMOD.Recipes.RecipesKetherWeapons;
import com.KMOD.Recipes.RecipesRevertedKetherGemBlocks;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.EntityList;
import net.minecraft.entity.EntityList.EntityEggInfo;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.DimensionManager;
import net.minecraftforge.common.util.EnumHelper;

@Mod(
   modid = "Real Kether",
   version = "Alpha 1.9.4",
   name = "The Real Kether"
)
public class KMOD_Main {
   public static final String MODID = "Real Kether";
   public static final String MODIDFORMOBS = "real kether";
   public static final String VERSION = "Alpha 1.9.4";
   @Instance
   public static KMOD_Main instance;
   @SidedProxy(
      clientSide = "com.KMOD.Main.ClientProxy",
      serverSide = "com.KMOD.Main.ServerProxy"
   )
   public static ServerProxy serverSide;
   public static ClientProxy clientSide;
   static int startEntityId = 300;
   public static final int KetherDimID = 8;
   public static BiomeGenBase KetherBiome;
   public static Block MagicStone;
   public static Block KetherDirt;
   public static Block KetherGrass;
   public static Block KetherPortal;
   public static BlockKetherBlock KetherCloud;
   public static Block KetherLeaves;
   public static Block KetherLog;
   public static Block KetherPlanks;
   public static Block KetherTallGrass;
   public static Block SapphireOre;
   public static Block RubyOre;
   public static Block TopazOre;
   public static Block LonsdaleiteOre;
   public static Block Hemp;
   public static Block KetherLonsdaleiteLeaves;
   public static Block KetherLonsdaleiteLog;
   public static Block KetherYellowFlower;
   public static Block KetherBlueFlower;
   public static Block KetherRedFlower;
   public static Block SapphireBlock;
   public static Block RubyBlock;
   public static Block TopazBlock;
   public static Block LonsdaleiteBlock;
   public static Block Mycena;
   public static Block Crystals;
   public static Block BlueFruitBlock;
   public static Block KetherStone;
   public static BlockKetherBlock ScrableStone;
   public static Block ScrapyStone;
   public static Block ScrapyBrick;
   public static Block CarvedScrapyBrick;
   public static Block UnbreakbleKetherLog;
   public static Block UnbreakbleKetherLeaves;
   public static Block KetherStoneBrick;
   public static Block KetherRedStoneBrick;
   public static BlockKetherBlock KetherYellowStoneBrick;
   public static Block KetherBlueStoneBrick;
   public static BlockKetherBlock KetherGlowBrick;
   public static Block KetherMossyStone;
   public static Block KetherEnchantedStoneBrick;
   public static Block KetherStoneSquare;
   public static Block KetherStonePanel;
   public static Block KetherCobblestone;
   public static Block HealingFlower;
   public static Block KetherSapling;
   public static Block KetherStonePillarBase;
   public static Block KetherStonePillarCenter;
   public static Block KetherStonePillarTop;
   public static Block KetherBlueLeaves;
   public static Block KetherYellowStoneBrickPillarBase;
   public static Block KetherYellowStoneBrickPillarCenter;
   public static Block KetherYellowStoneBrickPillarTop;
   public static Block KetherBlackRose;
   public static Block KetherPurpleRose;
   public static Block KetherBlueRose;
   public static Block KetherLightBlueRose;
   public static Block LifeLeaves;
   public static Block LifeLog;
   public static Block EnergyConverter;
   public static Block EnergyConverterActive;
   public static Block GiftsBlock;
   public static Block EnergyEnchanter;
   public static Block EnergyEnchanterActive;
   public static Block MalachiteOre;
   public static Block MalachiteBlock;
   public static Block MalachiteTiles;
   public static Block AdamantiumOre;
   public static Block AdamantiumBlock;
   public static Block KetherMagicFlower;
   public static Block ShadowOre;
   public static Block ShadowBlock;
   public static Block SaintOre;
   public static Block SaintBlock;
   public static Block GlowingKetherGrass;
   public static Block KetherGoldenLeaves;
   public static Block MagicFruitBlock;
   public static Block MovingSands;
   public static Item KetherPortalLighter;
   public static Item SapphireGem;
   public static Item RubyGem;
   public static Item TopazGem;
   public static Item LonsdaleiteGem;
   public static Item SapphirePickaxe;
   public static Item SapphireAxe;
   public static Item SapphireHoe;
   public static Item SapphireShovel;
   public static Item SapphireSword;
   public static Item RubyPickaxe;
   public static Item RubyAxe;
   public static Item RubyHoe;
   public static Item RubyShovel;
   public static Item RubySword;
   public static Item TopazPickaxe;
   public static Item TopazAxe;
   public static Item TopazHoe;
   public static Item TopazShovel;
   public static Item TopazSword;
   public static Item LonsdaleitePickaxe;
   public static Item LonsdaleiteAxe;
   public static Item LonsdaleiteHoe;
   public static Item LonsdaleiteShovel;
   public static Item LonsdaleiteSword;
   public static Item RubyBoots;
   public static Item RubyLeggins;
   public static Item RubyChestplate;
   public static Item RubyHelmet;
   public static Item SapphireBoots;
   public static Item SapphireLeggins;
   public static Item SapphireChestplate;
   public static Item SapphireHelmet;
   public static Item TopazBoots;
   public static Item TopazLeggins;
   public static Item TopazChestplate;
   public static Item TopazHelmet;
   public static Item LonsdaleiteBoots;
   public static Item LonsdaleiteLeggins;
   public static Item LonsdaleiteChestplate;
   public static Item LonsdaleiteHelmet;
   public static Item Weed;
   public static Item Joint;
   public static Item YellowFlowerEssence;
   public static Item BlueFlowerEssence;
   public static Item RedFlowerEssence;
   public static Item JumpBoots;
   public static Item KetherBlueWand;
   public static Item KetherRedWand;
   public static Item KetherYellowWand;
   public static Item KetherWand;
   public static Item KetherEnergy;
   public static Item HermesBoots;
   public static Item DarkEnergy;
   public static Item BlueFruit;
   public static Item KetherStatue;
   public static Item DemonEyeSummoner;
   public static Item KetherKey;
   public static Item Pytajnik;
   public static Item LegendaryMagicWand;
   public static Item KetherCrocodileLeather;
   public static Item KetherCrocodileTooth;
   public static Item APieceOfCloth;
   public static Item FullCloth;
   public static Item GravityWand;
   public static Item SmallWings;
   public static Item Wings;
   public static ItemEnergyCrystal EnergyCrystal;
   public static Item Malachite;
   public static Item CloudDust;
   public static Item CottonCandy;
   public static Item AdamantiumIngot;
   public static Item AdamantiumBoots;
   public static Item AdamantiumLeggins;
   public static Item AdamantiumChestplate;
   public static Item AdamantiumHelmet;
   public static Item AdamantiumPickaxe;
   public static Item AdamantiumAxe;
   public static Item AdamantiumHoe;
   public static Item AdamantiumShovel;
   public static Item AdamantiumSword;
   public static Item ShadowGem;
   public static Item ShadowBoots;
   public static Item ShadowLeggins;
   public static Item ShadowChestplate;
   public static Item ShadowHelmet;
   public static Item ShadowPickaxe;
   public static Item ShadowAxe;
   public static Item ShadowHoe;
   public static Item ShadowShovel;
   public static Item ShadowSword;
   public static Item MidasHand;
   public static Item MagicFruit;
   public static Item LameMeat;
   public static Item Venison;
   public static Item SaintGem;
   public static Item SaintBoots;
   public static Item SaintLeggins;
   public static Item SaintChestplate;
   public static Item SaintHelmet;
   public static Item SaintPickaxe;
   public static Item SaintAxe;
   public static Item SaintHoe;
   public static Item SaintShovel;
   public static Item SaintSword;
   public static final ToolMaterial SAPPHIRE = EnumHelper.addToolMaterial("SAPPHIRE", 3, 1000, 9.0F, 3.0F, 20);
   public static final ToolMaterial Ruby = EnumHelper.addToolMaterial("RUBY", 3, 1000, 9.0F, 3.0F, 20);
   public static final ToolMaterial Topaz = EnumHelper.addToolMaterial("TOPAZ", 3, 1000, 9.0F, 3.0F, 20);
   public static final ToolMaterial Shadow = EnumHelper.addToolMaterial("SHADOW", 3, 1500, 10.0F, 4.0F, 25);
   public static final ToolMaterial Saint = EnumHelper.addToolMaterial("SAINT", 3, 2000, 13.0F, 5.0F, 30);
   public static final ToolMaterial Lonsdaleite = EnumHelper.addToolMaterial("LONSDALEITE", 3, 2396, 14.0F, 5.0F, 35);
   public static final ToolMaterial Adamantium = EnumHelper.addToolMaterial("ADAMANTIUM", 3, 10000, 18.0F, 7.0F, 50);
   public static final ArmorMaterial SapphireArmor = EnumHelper.addArmorMaterial("SAPPHIRE", 28, new int[]{2, 7, 5, 2}, 7);
   public static final ArmorMaterial RubyArmor = EnumHelper.addArmorMaterial("RUBY", 28, new int[]{2, 7, 5, 2}, 7);
   public static final ArmorMaterial TopazArmor = EnumHelper.addArmorMaterial("TOPAZ", 28, new int[]{2, 7, 5, 2}, 7);
   public static final ArmorMaterial ShadowArmor = EnumHelper.addArmorMaterial("SHADOW", 33, new int[]{2, 7, 6, 6}, 8);
   public static final ArmorMaterial SaintArmor = EnumHelper.addArmorMaterial("SAINT", 35, new int[]{3, 8, 7, 7}, 14);
   public static final ArmorMaterial LonsdaleiteArmor = EnumHelper.addArmorMaterial("LONSDALEITE", 36, new int[]{4, 9, 7, 4}, 13);
   public static final ArmorMaterial SPECIAL = EnumHelper.addArmorMaterial("SPECIAL", 5, new int[]{1, 6, 4, 1}, 5);
   public static final ArmorMaterial AdamantiumArmor = EnumHelper.addArmorMaterial("ADAMANTIUM", 42, new int[]{5, 10, 9, 6}, 16);
   public static CreativeTabs KetherTab = new KetherCreativeTab(CreativeTabs.getNextID(), "Kether Tab");
   EventWorldGenMagicStoneOnly eventmanager1 = new EventWorldGenMagicStoneOnly();
   EventWorldGenKether eventmanager2 = new EventWorldGenKether();
   public static int CumulatedEnergy;
   public static int Satisfaction = 5000;

   public boolean isSHostile() {
      return Satisfaction < 0;
   }

   public boolean isSBest() {
      return Satisfaction > 10100;
   }

   public int getSEtap() {
      if (Satisfaction >= 0 && Satisfaction <= 999) {
         return 1;
      } else if (Satisfaction >= 1000 && Satisfaction <= 1999) {
         return 2;
      } else if (Satisfaction >= 2000 && Satisfaction <= 2999) {
         return 3;
      } else if (Satisfaction >= 3000 && Satisfaction <= 3999) {
         return 4;
      } else if (Satisfaction >= 4000 && Satisfaction <= 4999) {
         return 5;
      } else if (Satisfaction >= 5000 && Satisfaction <= 5999) {
         return 6;
      } else if (Satisfaction >= 6000 && Satisfaction <= 6999) {
         return 7;
      } else if (Satisfaction >= 7000 && Satisfaction <= 7999) {
         return 8;
      } else if (Satisfaction >= 8000 && Satisfaction <= 8999) {
         return 9;
      } else if (Satisfaction >= 9000 && Satisfaction <= 10000) {
         return 10;
      } else if (Satisfaction > 10001) {
         return 11;
      } else {
         return Satisfaction < 1 ? 0 : 100;
      }
   }

   @EventHandler
   public void preInit(FMLPreInitializationEvent event) {
      KMOD_Main_Entities.init();
      serverSide.registerRenderThings();
   }

   @EventHandler
   public void init(FMLInitializationEvent event) {
      NetworkRegistry.INSTANCE.registerGuiHandler(this, new EventGuiHandler());
      KetherBiome = new BiomeGenBaseKether(100);
      KetherDirt = (new BlockKetherDirt()).setCreativeTab(KetherTab).setHardness(0.5F).setStepSound(Block.soundTypeGravel).setBlockName("Kether Dirt");
      KetherGrass = (new BlockKetherGrass()).setCreativeTab(KetherTab).setHardness(0.6F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Grass");
      KetherPortal = (new BlockKetherPortal()).setCreativeTab(KetherTab).setHardness(-1.0F).setStepSound(Block.soundTypeGlass).setLightLevel(0.75F).setBlockName("Kether Portal");
      MagicStone = (new BlockMagicStone()).setCreativeTab(KetherTab).setHardness(1.0F).setBlockName("Magic Stone");
      KetherCloud = (BlockKetherBlock)(new BlockKetherCloud()).setCreativeTab(KetherTab).setHardness(0.3F).setStepSound(Block.soundTypeCloth).setBlockName("Kether Cloud");
      KetherLeaves = (new BlockKetherLeaves()).setCreativeTab(KetherTab).setHardness(0.2F).setLightOpacity(1).setStepSound(Block.soundTypeGrass).setBlockName("Kether Leaves");
      KetherLog = (new BlockKetherLog()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeWood).setBlockName("Kether Log");
      KetherPlanks = (new BlockKetherPlanks()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeWood).setBlockName("Kether Planks");
      KetherTallGrass = (new BlockKetherTallGrass()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Tall Grass");
      SapphireOre = new BlockKetherOre(3.5F, "Sapphire Ore");
      TopazOre = new BlockKetherOre(3.5F, "Topaz Ore");
      RubyOre = new BlockKetherOre(3.5F, "Ruby Ore");
      LonsdaleiteOre = new BlockKetherOre(5.5F, "Lonsdaleite Ore");
      Hemp = (new BlockHemp()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Hemp");
      KetherLonsdaleiteLeaves = (new BlockKetherLeaves()).setCreativeTab(KetherTab).setHardness(0.2F).setLightOpacity(1).setStepSound(Block.soundTypeGrass).setBlockName("Kether Lonsdaleite Leaves");
      KetherLonsdaleiteLog = (new BlockKetherLog()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeWood).setBlockName("Kether Lonsdaleite Log");
      KetherYellowFlower = (new BlockKetherFlower()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Yellow Flower").setLightLevel(0.345F);
      KetherBlueFlower = (new BlockKetherFlower()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Blue Flower").setLightLevel(0.345F);
      KetherRedFlower = (new BlockKetherFlower()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Red Flower").setLightLevel(0.345F);
      KetherSapling = (new BlockKetherSapling()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Sapling");
      SapphireBlock = new BlockKetherGemBlock("Sapphire Block");
      RubyBlock = new BlockKetherGemBlock("Ruby Block");
      TopazBlock = new BlockKetherGemBlock("Topaz Block");
      LonsdaleiteBlock = new BlockKetherGemBlock("Lonsdaleite Block");
      Mycena = (new BlockKetherMycena()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeWood).setBlockName("Mycena").setLightLevel(0.735F);
      Crystals = (new BlockKetherCrystals()).setCreativeTab(KetherTab).setHardness(50.0F).setStepSound(Block.soundTypeStone).setBlockName("Crystals").setLightLevel(1.0F);
      BlueFruitBlock = (new BlockBlueFruit()).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Blue Fruit Block");
      KetherStone = new BlockKetherStone("Kether Stone");
      ScrableStone = new BlockKetherBlock("Scrable Stone");
      ScrapyStone = new BlockKetherBlock("Scrapy Stone");
      ScrapyBrick = new BlockKetherBlock("Scrapy Brick");
      CarvedScrapyBrick = new BlockKetherBlock("Carved Scrapy Brick");
      UnbreakbleKetherLeaves = (new BlockUnbreakableKetherLeaves()).setCreativeTab(KetherTab).setHardness(-1.0F).setLightOpacity(1).setStepSound(Block.soundTypeGrass).setBlockName("Unbreakable Kether Leaves");
      UnbreakbleKetherLog = (new BlockUnbreakableKetherLog()).setCreativeTab(KetherTab).setHardness(-1.0F).setStepSound(Block.soundTypeWood).setBlockName("Unbreakable Kether Log");
      KetherStoneBrick = new BlockKetherBlock("Kether Stone Brick");
      KetherRedStoneBrick = new BlockKetherBlock("Kether Red Stone Brick");
      KetherBlueStoneBrick = new BlockKetherBlock("Kether Blue Stone Brick");
      KetherYellowStoneBrick = new BlockKetherBlock("Kether Yellow Stone Brick");
      KetherGlowBrick = (BlockKetherBlock)(new BlockKetherBlock("Kether Glow Brick")).setLightLevel(0.7F);
      KetherMossyStone = new BlockKetherBlock("Kether Mossy Stone");
      KetherEnchantedStoneBrick = new BlockKetherBlock("Kether Enchanted Stone Brick");
      KetherStoneSquare = new BlockKetherBlock("Kether Stone Square");
      KetherStonePanel = new BlockKetherBlock("Kether Stone Panel");
      KetherCobblestone = new BlockKetherBlock("Kether Cobblestone");
      HealingFlower = (new BlockHealingFlower()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Healing Flower").setLightLevel(0.335F);
      KetherStonePillarBase = (new BlockKetherPillar()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeStone).setBlockName("Kether Stone Pillar Base");
      KetherStonePillarCenter = (new BlockKetherPillar()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeStone).setBlockName("Kether Stone Pillar Center");
      KetherStonePillarTop = (new BlockKetherPillar()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeStone).setBlockName("Kether Stone Pillar Top");
      KetherBlueLeaves = (new BlockKetherLeaves()).setCreativeTab(KetherTab).setHardness(0.2F).setLightOpacity(1).setStepSound(Block.soundTypeGrass).setBlockName("Kether Blue Leaves");
      KetherYellowStoneBrickPillarBase = (new BlockKetherPillar()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeStone).setBlockName("Kether Yellow Stone Brick Pillar Base");
      KetherYellowStoneBrickPillarCenter = (new BlockKetherPillar()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeStone).setBlockName("Kether Yellow Stone Brick Pillar Center");
      KetherYellowStoneBrickPillarTop = (new BlockKetherPillar()).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeStone).setBlockName("Kether Yellow Stone Brick Pillar Top");
      KetherBlackRose = (new BlockKetherRose()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Black Rose");
      KetherBlueRose = (new BlockKetherRose()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Blue Rose");
      KetherPurpleRose = (new BlockKetherRose()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Purple Rose");
      KetherLightBlueRose = (new BlockKetherRose()).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Kether Light Blue Rose");
      LifeLeaves = (new BlockLifeLeaves()).setCreativeTab((CreativeTabs)null).setHardness(0.2F).setLightOpacity(1).setStepSound(Block.soundTypeGrass).setBlockName("Life Leaves");
      LifeLog = (new BlockKetherLog()).setCreativeTab((CreativeTabs)null).setHardness(2.0F).setStepSound(Block.soundTypeWood).setBlockName("Kether Log");
      EnergyConverter = (new BlockEnergyConverter(false)).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeMetal).setBlockName("Energy Converter");
      EnergyConverterActive = (new BlockEnergyConverter(true)).setCreativeTab((CreativeTabs)null).setHardness(2.0F).setStepSound(Block.soundTypeMetal).setBlockName("Energy Converter");
      GiftsBlock = (new BlockGiftsBlock()).setCreativeTab((CreativeTabs)null).setHardness(-1.0F).setStepSound(Block.soundTypeMetal).setBlockName("Gifts Block");
      EnergyEnchanter = (new BlockEnergyEnchanter(false)).setCreativeTab(KetherTab).setHardness(2.0F).setStepSound(Block.soundTypeMetal).setBlockName("Energy Enchanter");
      EnergyEnchanterActive = (new BlockEnergyEnchanter(true)).setCreativeTab((CreativeTabs)null).setHardness(2.0F).setStepSound(Block.soundTypeMetal).setBlockName("Energy Enchanter");
      MalachiteOre = new BlockKetherOre(3.5F, "Malachite Ore");
      MalachiteBlock = new BlockKetherGemBlock("Malachite Block");
      MalachiteTiles = new BlockKetherBlock("Malachite Tiles");
      AdamantiumOre = new BlockKetherOre(50.0F, "Adamantium Ore");
      AdamantiumBlock = new BlockKetherGemBlock("Adamantium Block");
      KetherMagicFlower = (new BlockKetherMagicFlower("Kether Magic Flower")).setCreativeTab(KetherTab).setHardness(0.0F).setStepSound(Block.soundTypeGrass);
      ShadowOre = new BlockKetherOre(5.0F, "Shadow Ore");
      ShadowBlock = new BlockKetherGemBlock("Shadow Block");
      SaintOre = new BlockKetherOre(6.0F, "Saint Ore");
      SaintBlock = new BlockKetherGemBlock("Saint Block");
      GlowingKetherGrass = new BlockKetherGlowingGrass();
      KetherGoldenLeaves = (new BlockKetherLeaves()).setCreativeTab(KetherTab).setHardness(0.2F).setLightOpacity(1).setStepSound(Block.soundTypeGrass).setBlockName("Kether Golden Leaves");
      MagicFruitBlock = (new BlockMagicFruit()).setHardness(0.0F).setStepSound(Block.soundTypeGrass).setBlockName("Magic Fruit Block");
      MovingSands = (new BlockMovingSands("Moving Sands")).setHardness(1.0F).setStepSound(Block.soundTypeGravel).setBlockName("Moving Sands");
      KetherPortalLighter = (new ItemKetherLighter()).setCreativeTab(KetherTab).setUnlocalizedName("Kether Portal Lighter");
      SapphirePickaxe = new ItemKetherPickaxe(SAPPHIRE, "Sapphire Pickaxe");
      SapphireAxe = new ItemKetherAxe(SAPPHIRE, "Sapphire Axe");
      SapphireHoe = new ItemKetherHoe(SAPPHIRE, "Sapphire Hoe");
      SapphireShovel = new ItemKetherShovel(SAPPHIRE, "Sapphire Shovel");
      SapphireSword = new ItemKetherSword(SAPPHIRE, "Sapphire Sword");
      RubyPickaxe = new ItemKetherPickaxe(Ruby, "Ruby Pickaxe");
      RubyAxe = new ItemKetherAxe(Ruby, "Ruby Axe");
      RubyHoe = new ItemKetherHoe(Ruby, "Ruby Hoe");
      RubyShovel = new ItemKetherShovel(Ruby, "Ruby Shovel");
      RubySword = new ItemKetherSword(Ruby, "Ruby Sword");
      TopazPickaxe = new ItemKetherPickaxe(Topaz, "Topaz Pickaxe");
      TopazAxe = new ItemKetherAxe(Topaz, "Topaz Axe");
      TopazHoe = new ItemKetherHoe(Topaz, "Topaz Hoe");
      TopazShovel = new ItemKetherShovel(Topaz, "Topaz Shovel");
      TopazSword = new ItemKetherSword(Topaz, "Topaz Sword");
      LonsdaleitePickaxe = new ItemKetherPickaxe(Lonsdaleite, "Lonsdaleite Pickaxe");
      LonsdaleiteAxe = new ItemKetherAxe(Lonsdaleite, "Lonsdaleite Axe");
      LonsdaleiteHoe = new ItemKetherHoe(Lonsdaleite, "Lonsdaleite Hoe");
      LonsdaleiteShovel = new ItemKetherShovel(Lonsdaleite, "Lonsdaleite Shovel");
      LonsdaleiteSword = new ItemKetherSword(Lonsdaleite, "Lonsdaleite Sword");
      SapphireGem = new ItemKether("Sapphire Gem");
      TopazGem = new ItemKether("Topaz Gem");
      RubyGem = new ItemKether("Ruby Gem");
      LonsdaleiteGem = new ItemKether("Lonsdaleite Gem");
      Weed = new ItemKether("Weed");
      Joint = (new ItemJoint(0, false)).setCreativeTab(KetherTab).setUnlocalizedName("Joint");
      SapphireBoots = (new ItemKetherArmor(SapphireArmor, serverSide.addArmor("SAPPHIRE"), 3, "Sapphire Boots")).setUnlocalizedName("Sapphire Boots");
      SapphireLeggins = (new ItemKetherArmor(SapphireArmor, serverSide.addArmor("SAPPHIRE"), 2, "Sapphire Leggins")).setUnlocalizedName("Sapphire Leggins");
      SapphireChestplate = (new ItemKetherArmor(SapphireArmor, serverSide.addArmor("SAPPHIRE"), 1, "Sapphire Chestplate")).setUnlocalizedName("Sapphire Chestplate");
      SapphireHelmet = (new ItemKetherArmor(SapphireArmor, serverSide.addArmor("SAPPHIRE"), 0, "Sapphire Helmet")).setUnlocalizedName("Sapphire Helmet");
      TopazBoots = (new ItemKetherArmor(TopazArmor, serverSide.addArmor("Topaz"), 3, "Topaz Boots")).setUnlocalizedName("Topaz Boots");
      TopazLeggins = (new ItemKetherArmor(TopazArmor, serverSide.addArmor("Topaz"), 2, "Topaz Leggins")).setUnlocalizedName("Topaz Leggins");
      TopazChestplate = (new ItemKetherArmor(TopazArmor, serverSide.addArmor("Topaz"), 1, "Topaz Chestplate")).setUnlocalizedName("Topaz Chestplate");
      TopazHelmet = (new ItemKetherArmor(TopazArmor, serverSide.addArmor("Topaz"), 0, "Topaz Helmet")).setUnlocalizedName("Topaz Helmet");
      RubyBoots = (new ItemKetherArmor(RubyArmor, serverSide.addArmor("Ruby"), 3, "Ruby Boots")).setUnlocalizedName("Ruby Boots");
      RubyLeggins = (new ItemKetherArmor(RubyArmor, serverSide.addArmor("Ruby"), 2, "Ruby Leggins")).setUnlocalizedName("Ruby Leggins");
      RubyChestplate = (new ItemKetherArmor(RubyArmor, serverSide.addArmor("Ruby"), 1, "Ruby Chestplate")).setUnlocalizedName("Ruby Chestplate");
      RubyHelmet = (new ItemKetherArmor(RubyArmor, serverSide.addArmor("Ruby"), 0, "Ruby Helmet")).setUnlocalizedName("Ruby Helmet");
      LonsdaleiteBoots = (new ItemKetherArmor(LonsdaleiteArmor, serverSide.addArmor("Lonsdaleite"), 3, "Lonsdaleite Boots")).setUnlocalizedName("Lonsdaleite Boots");
      LonsdaleiteLeggins = (new ItemKetherArmor(LonsdaleiteArmor, serverSide.addArmor("Lonsdaleite"), 2, "Lonsdaleite Leggins")).setUnlocalizedName("Lonsdaleite Leggins");
      LonsdaleiteChestplate = (new ItemKetherArmor(LonsdaleiteArmor, serverSide.addArmor("Lonsdaleite"), 1, "Lonsdaleite Chestplate")).setUnlocalizedName("Lonsdaleite Chestplate");
      LonsdaleiteHelmet = (new ItemKetherArmor(LonsdaleiteArmor, serverSide.addArmor("Lonsdaleite"), 0, "Lonsdaleite Helmet")).setUnlocalizedName("Lonsdaleite Helmet");
      YellowFlowerEssence = new ItemKether("Yellow Flower Essence");
      BlueFlowerEssence = new ItemKether("Blue Flower Essence");
      RedFlowerEssence = new ItemKether("Red Flower Essence");
      JumpBoots = (new ItemKetherArmor(SPECIAL, serverSide.addArmor("Jump Boots"), 3, "Jump Boots")).setUnlocalizedName("Jump Boots");
      KetherBlueWand = new ItemKetherWand("Kether Blue Wand");
      KetherRedWand = new ItemKetherWand("Kether Red Wand");
      KetherYellowWand = new ItemKetherWand("Kether Yellow Wand");
      KetherWand = new ItemKetherWand("Kether Wand");
      KetherEnergy = new ItemKether("Kether Energy");
      HermesBoots = (new ItemKetherArmor(SPECIAL, serverSide.addArmor("Hermes Boots"), 3, "Hermes Boots")).setUnlocalizedName("Hermes Boots");
      DarkEnergy = new ItemKether("Dark Energy");
      BlueFruit = new ItemBlueFruit(4, 5.0F, BlueFruitBlock, KetherGrass, "Blue Fruit");
      KetherStatue = new ItemKether("Kether Statue");
      DemonEyeSummoner = new ItemKether("Demon Eye Summoner");
      KetherKey = new ItemKether("Kether Key");
      Pytajnik = new ItemKether("Pytajnik");
      LegendaryMagicWand = new ItemLegendaryMagicWand("Legendary Magic Wand");
      KetherCrocodileLeather = new ItemKether("Kether Crocodile Leather");
      KetherCrocodileTooth = new ItemKether("Kether Crocodile Tooth");
      APieceOfCloth = new ItemKether("A Piece Of Cloth");
      FullCloth = new ItemKether("Full Cloth");
      GravityWand = new ItemGravityWand("Gravity Wand");
      SmallWings = new ItemKether("Small Wings");
      Wings = new ItemKether("Wings");
      EnergyCrystal = new ItemEnergyCrystal("Energy Crystal");
      Malachite = new ItemKether("Malachite");
      CloudDust = new ItemKether("Cloud Dust");
      CottonCandy = (new ItemCottonCandy(3, 0.3F, false)).setCreativeTab(KetherTab).setUnlocalizedName("Cotton Candy");
      AdamantiumIngot = new ItemKether("Adamantium Ingot");
      AdamantiumPickaxe = new ItemKetherPickaxe(Adamantium, "Adamantium Pickaxe");
      AdamantiumAxe = new ItemKetherAxe(Adamantium, "Adamantium Axe");
      AdamantiumHoe = new ItemKetherHoe(Adamantium, "Adamantium Hoe");
      AdamantiumShovel = new ItemKetherShovel(Adamantium, "Adamantium Shovel");
      AdamantiumSword = new ItemKetherSword(Adamantium, "Adamantium Sword");
      AdamantiumBoots = (new ItemKetherArmor(AdamantiumArmor, serverSide.addArmor("Adamantium"), 3, "Adamantium Boots")).setUnlocalizedName("Adamantium Boots");
      AdamantiumLeggins = (new ItemKetherArmor(AdamantiumArmor, serverSide.addArmor("Adamantium"), 2, "Adamantium Leggins")).setUnlocalizedName("Adamantium Leggins");
      AdamantiumChestplate = (new ItemKetherArmor(AdamantiumArmor, serverSide.addArmor("Adamantium"), 1, "Adamantium Chestplate")).setUnlocalizedName("Adamantium Chestplate");
      AdamantiumHelmet = (new ItemKetherArmor(AdamantiumArmor, serverSide.addArmor("Adamantium"), 0, "Adamantium Helmet")).setUnlocalizedName("Adamantium Helmet");
      ShadowGem = new ItemKether("Shadow Gem");
      ShadowPickaxe = new ItemKetherPickaxe(Shadow, "Shadow Pickaxe");
      ShadowAxe = new ItemKetherAxe(Shadow, "Shadow Axe");
      ShadowHoe = new ItemKetherHoe(Shadow, "Shadow Hoe");
      ShadowShovel = new ItemKetherShovel(Shadow, "Shadow Shovel");
      ShadowSword = new ItemKetherSword(Shadow, "Shadow Sword");
      ShadowBoots = (new ItemKetherArmor(ShadowArmor, serverSide.addArmor("Shadow"), 3, "Shadow Boots")).setUnlocalizedName("Shadow Boots");
      ShadowLeggins = (new ItemKetherArmor(ShadowArmor, serverSide.addArmor("Shadow"), 2, "Shadow Leggins")).setUnlocalizedName("Shadow Leggins");
      ShadowChestplate = (new ItemKetherArmor(ShadowArmor, serverSide.addArmor("Shadow"), 1, "Shadow Chestplate")).setUnlocalizedName("Shadow Chestplate");
      ShadowHelmet = (new ItemKetherArmor(ShadowArmor, serverSide.addArmor("Shadow"), 0, "Shadow Helmet")).setUnlocalizedName("Shadow Helmet");
      SaintGem = new ItemKether("Saint Gem");
      SaintPickaxe = new ItemKetherPickaxe(Saint, "Saint Pickaxe");
      SaintAxe = new ItemKetherAxe(Saint, "Saint Axe");
      SaintHoe = new ItemKetherHoe(Saint, "Saint Hoe");
      SaintShovel = new ItemKetherShovel(Saint, "Saint Shovel");
      SaintSword = new ItemKetherSword(Saint, "Saint Sword");
      SaintBoots = (new ItemKetherArmor(SaintArmor, serverSide.addArmor("Saint"), 3, "Saint Boots")).setUnlocalizedName("Saint Boots");
      SaintLeggins = (new ItemKetherArmor(SaintArmor, serverSide.addArmor("Saint"), 2, "Saint Leggins")).setUnlocalizedName("Saint Leggins");
      SaintChestplate = (new ItemKetherArmor(SaintArmor, serverSide.addArmor("Saint"), 1, "Saint Chestplate")).setUnlocalizedName("Saint Chestplate");
      SaintHelmet = (new ItemKetherArmor(SaintArmor, serverSide.addArmor("Saint"), 0, "Saint Helmet")).setUnlocalizedName("Saint Helmet");
      MidasHand = new ItemKether("Midas Hand");
      MagicFruit = new ItemMagicFruit(6, 1.0F, MagicFruitBlock, KetherCloud, "Magic Fruit");
      LameMeat = (new ItemCottonCandy(4, 0.4F, false)).setCreativeTab(KetherTab).setUnlocalizedName("Lame Meat");
      Venison = (new ItemCottonCandy(4, 0.5F, false)).setCreativeTab(KetherTab).setUnlocalizedName("Venison");
      GameRegistry.registerItem(SapphireGem, "Sapphire Gem");
      GameRegistry.registerItem(TopazGem, "Topaz Gem");
      GameRegistry.registerItem(RubyGem, "Ruby Gem");
      GameRegistry.registerItem(LonsdaleiteGem, "Lonsdaleite Gem");
      GameRegistry.registerItem(SapphirePickaxe, "Sapphire Pickaxe");
      GameRegistry.registerItem(SapphireAxe, "Sapphire Axe");
      GameRegistry.registerItem(SapphireHoe, "Sapphire Hoe");
      GameRegistry.registerItem(SapphireShovel, "Sapphire Shovel");
      GameRegistry.registerItem(SapphireSword, "Sapphire Sword");
      GameRegistry.registerItem(KetherPortalLighter, "Kether Portal Lighter");
      GameRegistry.registerItem(RubyPickaxe, "Ruby Pickaxe");
      GameRegistry.registerItem(RubyAxe, "Ruby Axe");
      GameRegistry.registerItem(RubyHoe, "Ruby Hoe");
      GameRegistry.registerItem(RubyShovel, "Ruby Shovel");
      GameRegistry.registerItem(RubySword, "Ruby Sword");
      GameRegistry.registerItem(TopazPickaxe, "Topaz Pickaxe");
      GameRegistry.registerItem(TopazAxe, "Topaz Axe");
      GameRegistry.registerItem(TopazHoe, "Topaz Hoe");
      GameRegistry.registerItem(TopazShovel, "Topaz Shovel");
      GameRegistry.registerItem(TopazSword, "Topaz Sword");
      GameRegistry.registerItem(LonsdaleitePickaxe, "Lonsdaleite Pickaxe");
      GameRegistry.registerItem(LonsdaleiteAxe, "Lonsdaleite Axe");
      GameRegistry.registerItem(LonsdaleiteHoe, "Lonsdaleite Hoe");
      GameRegistry.registerItem(LonsdaleiteShovel, "Lonsdaleite Shovel");
      GameRegistry.registerItem(LonsdaleiteSword, "Lonsdaleite Sword");
      GameRegistry.registerItem(Weed, "Weed");
      GameRegistry.registerItem(Joint, "Joint");
      GameRegistry.registerItem(SapphireBoots, "Sapphire Boots");
      GameRegistry.registerItem(SapphireLeggins, "Sapphire Leggins");
      GameRegistry.registerItem(SapphireChestplate, "Sapphire Chestplate");
      GameRegistry.registerItem(SapphireHelmet, "Sapphire Helmet");
      GameRegistry.registerItem(TopazBoots, "Topaz Boots");
      GameRegistry.registerItem(TopazLeggins, "Topaz Leggins");
      GameRegistry.registerItem(TopazChestplate, "Topaz Chestplate");
      GameRegistry.registerItem(TopazHelmet, "Topaz Helmet");
      GameRegistry.registerItem(RubyBoots, "Ruby Boots");
      GameRegistry.registerItem(RubyLeggins, "Ruby Leggins");
      GameRegistry.registerItem(RubyChestplate, "Ruby Chestplate");
      GameRegistry.registerItem(RubyHelmet, "Ruby Helmet");
      GameRegistry.registerItem(LonsdaleiteBoots, "Lonsdaleite Boots");
      GameRegistry.registerItem(LonsdaleiteLeggins, "Lonsdaleite Leggins");
      GameRegistry.registerItem(LonsdaleiteChestplate, "Lonsdaleite Chestplate");
      GameRegistry.registerItem(LonsdaleiteHelmet, "Lonsdaleite Helmet");
      GameRegistry.registerItem(YellowFlowerEssence, "Yellow Flower Essence");
      GameRegistry.registerItem(BlueFlowerEssence, "Blue Flower Essence");
      GameRegistry.registerItem(RedFlowerEssence, "Red Flower Essence");
      GameRegistry.registerItem(JumpBoots, "Jump Boots");
      GameRegistry.registerItem(KetherBlueWand, "Kether Blue Wand");
      GameRegistry.registerItem(KetherRedWand, "Kether Red Wand");
      GameRegistry.registerItem(KetherYellowWand, "Kether Yellow Wand");
      GameRegistry.registerItem(KetherWand, "Kether Wand");
      GameRegistry.registerItem(KetherEnergy, "Kether Energy");
      GameRegistry.registerItem(HermesBoots, "Hermes Boots");
      GameRegistry.registerItem(DarkEnergy, "Dark Energy");
      GameRegistry.registerItem(BlueFruit, "Blue Fruit");
      GameRegistry.registerItem(KetherStatue, "Kether Statue");
      GameRegistry.registerItem(DemonEyeSummoner, "Demon Eye Summoner");
      GameRegistry.registerItem(KetherKey, "Kether Key");
      GameRegistry.registerItem(Pytajnik, "Pytajnik");
      GameRegistry.registerItem(LegendaryMagicWand, "Legendary Magic Wand");
      GameRegistry.registerItem(KetherCrocodileLeather, "Kether Crocodile Leather");
      GameRegistry.registerItem(KetherCrocodileTooth, "Kether Crocodile Tooth");
      GameRegistry.registerItem(APieceOfCloth, "A Piece Of Cloth");
      GameRegistry.registerItem(FullCloth, "Full Cloth");
      GameRegistry.registerItem(GravityWand, "Gravity Wand");
      GameRegistry.registerItem(SmallWings, "Small Wings");
      GameRegistry.registerItem(Wings, "Wings");
      GameRegistry.registerItem(EnergyCrystal, "Energy Crystal");
      GameRegistry.registerItem(Malachite, "Malachite");
      GameRegistry.registerItem(CloudDust, "Cloud Dust");
      GameRegistry.registerItem(CottonCandy, "Cotton Candy");
      GameRegistry.registerItem(AdamantiumIngot, "Adamantium Ingot");
      GameRegistry.registerItem(AdamantiumBoots, "Adamantium Boots");
      GameRegistry.registerItem(AdamantiumLeggins, "Adamantium Leggins");
      GameRegistry.registerItem(AdamantiumChestplate, "Adamantium Chestplate");
      GameRegistry.registerItem(AdamantiumHelmet, "Adamantium Helmet");
      GameRegistry.registerItem(AdamantiumPickaxe, "Adamantium Pickaxe");
      GameRegistry.registerItem(AdamantiumAxe, "Adamantium Axe");
      GameRegistry.registerItem(AdamantiumHoe, "Adamantium Hoe");
      GameRegistry.registerItem(AdamantiumShovel, "Adamantium Shovel");
      GameRegistry.registerItem(AdamantiumSword, "Adamantium Sword");
      GameRegistry.registerItem(ShadowGem, "Shadow Gem");
      GameRegistry.registerItem(ShadowBoots, "Shadow Boots");
      GameRegistry.registerItem(ShadowLeggins, "Shadow Leggins");
      GameRegistry.registerItem(ShadowChestplate, "Shadow Chestplate");
      GameRegistry.registerItem(ShadowHelmet, "Shadow Helmet");
      GameRegistry.registerItem(ShadowPickaxe, "Shadow Pickaxe");
      GameRegistry.registerItem(ShadowAxe, "Shadow Axe");
      GameRegistry.registerItem(ShadowHoe, "Shadow Hoe");
      GameRegistry.registerItem(ShadowShovel, "Shadow Shovel");
      GameRegistry.registerItem(ShadowSword, "Shadow Sword");
      GameRegistry.registerItem(SaintGem, "Saint Gem");
      GameRegistry.registerItem(SaintBoots, "Saint Boots");
      GameRegistry.registerItem(SaintLeggins, "Saint Leggins");
      GameRegistry.registerItem(SaintChestplate, "Saint Chestplate");
      GameRegistry.registerItem(SaintHelmet, "Saint Helmet");
      GameRegistry.registerItem(SaintPickaxe, "Saint Pickaxe");
      GameRegistry.registerItem(SaintAxe, "Saint Axe");
      GameRegistry.registerItem(SaintHoe, "Saint Hoe");
      GameRegistry.registerItem(SaintShovel, "Saint Shovel");
      GameRegistry.registerItem(SaintSword, "Saint Sword");
      GameRegistry.registerItem(MidasHand, "Midas Hand");
      GameRegistry.registerItem(MagicFruit, "Magic Fruit");
      GameRegistry.registerItem(LameMeat, "Lame Meat");
      GameRegistry.registerItem(Venison, "Venison");
      GameRegistry.registerBlock(KetherDirt, "Kether Dirt");
      GameRegistry.registerBlock(KetherGrass, "Kether Grass");
      GameRegistry.registerBlock(KetherPortal, "Kether Portal");
      GameRegistry.registerBlock(MagicStone, "Magic Stone");
      GameRegistry.registerBlock(KetherCloud, "Kether Cloud");
      GameRegistry.registerBlock(KetherLeaves, "Kether Leaves");
      GameRegistry.registerBlock(KetherLog, "Kether Log");
      GameRegistry.registerBlock(KetherTallGrass, "Kether Tall Grass,");
      GameRegistry.registerBlock(KetherPlanks, "Kether Planks");
      GameRegistry.registerBlock(SapphireOre, "Sapphire Ore");
      GameRegistry.registerBlock(RubyOre, "Ruby Ore");
      GameRegistry.registerBlock(TopazOre, "Topaz Ore");
      GameRegistry.registerBlock(LonsdaleiteOre, "Lonsdaleite Ore");
      GameRegistry.registerBlock(Hemp, "Hemp");
      GameRegistry.registerBlock(KetherLonsdaleiteLeaves, "Kether Lonsdaleite Leaves");
      GameRegistry.registerBlock(KetherLonsdaleiteLog, "Kether Lonsdaleite Log");
      GameRegistry.registerBlock(KetherYellowFlower, "Kether Yellow Flower");
      GameRegistry.registerBlock(KetherBlueFlower, "Kether Blue Flower");
      GameRegistry.registerBlock(KetherRedFlower, "Kether Red Flower");
      GameRegistry.registerBlock(KetherSapling, "Kether Sapling");
      GameRegistry.registerBlock(SapphireBlock, "Sapphire Block");
      GameRegistry.registerBlock(RubyBlock, "Ruby Block");
      GameRegistry.registerBlock(TopazBlock, "Topaz Block");
      GameRegistry.registerBlock(LonsdaleiteBlock, "Lonsdaleite Block");
      GameRegistry.registerBlock(Mycena, "Mycena");
      GameRegistry.registerBlock(Crystals, "Crystals");
      GameRegistry.registerBlock(BlueFruitBlock, "BlueFruitBlock");
      GameRegistry.registerBlock(KetherStone, "Kether Stone");
      GameRegistry.registerBlock(ScrableStone, "Scrable Stone");
      GameRegistry.registerBlock(ScrapyStone, "Scrapy Stone");
      GameRegistry.registerBlock(ScrapyBrick, "Scrapy Brick");
      GameRegistry.registerBlock(CarvedScrapyBrick, "Carved Scrapy Brick");
      GameRegistry.registerBlock(UnbreakbleKetherLeaves, "Unbreakble Kether Leaves");
      GameRegistry.registerBlock(UnbreakbleKetherLog, "Unbreakble Kether Log");
      GameRegistry.registerBlock(KetherStoneBrick, "Kether Stone Brick");
      GameRegistry.registerBlock(KetherRedStoneBrick, "Kether Red Stone Brick");
      GameRegistry.registerBlock(KetherBlueStoneBrick, "Kether Blue Stone Brick");
      GameRegistry.registerBlock(KetherYellowStoneBrick, "Kether Yellow Stone Brick");
      GameRegistry.registerBlock(KetherGlowBrick, "Kether Glow Brick");
      GameRegistry.registerBlock(KetherMossyStone, "Kether Mossy Stone");
      GameRegistry.registerBlock(KetherEnchantedStoneBrick, "Kether Enchanted Stone Brick");
      GameRegistry.registerBlock(KetherStoneSquare, "Kether Stone Square");
      GameRegistry.registerBlock(KetherStonePanel, "Kether Stone Panel");
      GameRegistry.registerBlock(KetherCobblestone, "Kether Cobblestone");
      GameRegistry.registerBlock(HealingFlower, "Healing Flower");
      GameRegistry.registerBlock(KetherStonePillarBase, "Kether Stone Pillar Base");
      GameRegistry.registerBlock(KetherStonePillarCenter, "Kether Stone Pillar Center");
      GameRegistry.registerBlock(KetherStonePillarTop, "Kether Stone Pillar Top");
      GameRegistry.registerBlock(KetherBlueLeaves, "Kether Blue Leaves");
      GameRegistry.registerBlock(KetherYellowStoneBrickPillarBase, "Kether Yellow Stone Brick Pillar Base");
      GameRegistry.registerBlock(KetherYellowStoneBrickPillarCenter, "Kether Yellow Stone Brick Pillar Center");
      GameRegistry.registerBlock(KetherYellowStoneBrickPillarTop, "Kether Yellow Stone Brick Pillar Top");
      GameRegistry.registerBlock(KetherBlackRose, "Kether Black Rose");
      GameRegistry.registerBlock(KetherBlueRose, "Kether Blue Rose");
      GameRegistry.registerBlock(KetherPurpleRose, "Kether Purple Rose");
      GameRegistry.registerBlock(KetherLightBlueRose, "Kether Light Blue Rose");
      GameRegistry.registerBlock(LifeLeaves, "Life Leaves");
      GameRegistry.registerBlock(LifeLog, "Life Log");
      GameRegistry.registerBlock(EnergyConverter, "Energy Converter");
      GameRegistry.registerBlock(EnergyConverterActive, "Energy Converter Active");
      GameRegistry.registerBlock(GiftsBlock, "Gifts Block");
      GameRegistry.registerBlock(EnergyEnchanter, "Energy Enchanter");
      GameRegistry.registerBlock(EnergyEnchanterActive, "Energy Enchanter Active");
      GameRegistry.registerBlock(MalachiteOre, "Malachite Ore");
      GameRegistry.registerBlock(MalachiteBlock, "Malachite Block");
      GameRegistry.registerBlock(MalachiteTiles, "Malachite Tiles");
      GameRegistry.registerBlock(AdamantiumOre, "Adamantium Ore");
      GameRegistry.registerBlock(AdamantiumBlock, "Adamantium Block");
      GameRegistry.registerBlock(KetherMagicFlower, "Kether Magic Flower");
      GameRegistry.registerBlock(ShadowOre, "Shadow Ore");
      GameRegistry.registerBlock(ShadowBlock, "Shadow Block");
      GameRegistry.registerBlock(SaintOre, "Saint Ore");
      GameRegistry.registerBlock(SaintBlock, "Saint Block");
      GameRegistry.registerBlock(GlowingKetherGrass, "Glowing Kether Grass");
      GameRegistry.registerBlock(KetherGoldenLeaves, "Kether Golden Leaves");
      GameRegistry.registerBlock(MagicFruitBlock, "MagicFruitBlock");
      GameRegistry.registerBlock(MovingSands, "Moving Sands");
      GameRegistry.addRecipe(new ItemStack(CottonCandy, 2), new Object[]{"YYY", "CXC", " X ", 'Y', CloudDust, 'X', Items.stick, 'C', Items.sugar});
      GameRegistry.addRecipe(new ItemStack(MalachiteTiles, 4), new Object[]{"YXY", "XYX", "YXY", 'Y', KetherStoneBrick, 'X', Malachite});
      GameRegistry.addRecipe(new ItemStack(EnergyEnchanter, 1), new Object[]{"YXY", "XYX", "XXX", 'Y', KetherStoneBrick, 'X', Crystals});
      GameRegistry.addRecipe(new ItemStack(EnergyCrystal, 1), new Object[]{"YYY", "YXY", "YYY", 'Y', Crystals, 'X', LonsdaleiteGem});
      GameRegistry.addRecipe(new ItemStack(EnergyConverter, 1), new Object[]{"YYY", "YXY", "YYY", 'Y', KetherStoneBrick, 'X', EnergyCrystal});
      GameRegistry.addRecipe(new ItemStack(Wings, 1), new Object[]{"YYY", "YYY", "YYY", 'Y', SmallWings});
      GameRegistry.addRecipe(new ItemStack(KetherYellowStoneBrickPillarTop, 1), new Object[]{"YYY", " Y ", " Y ", 'Y', KetherYellowStoneBrick});
      GameRegistry.addRecipe(new ItemStack(KetherYellowStoneBrickPillarCenter, 1), new Object[]{"Y Y", "Y Y", "Y Y", 'Y', KetherYellowStoneBrick});
      GameRegistry.addRecipe(new ItemStack(KetherYellowStoneBrickPillarBase, 1), new Object[]{" Y ", " Y ", "YYY", 'Y', KetherYellowStoneBrick});
      GameRegistry.addRecipe(new ItemStack(KetherStonePillarTop, 1), new Object[]{"YYY", " Y ", " Y ", 'Y', KetherCobblestone});
      GameRegistry.addRecipe(new ItemStack(KetherStonePillarCenter, 1), new Object[]{"Y Y", "Y Y", "Y Y", 'Y', KetherCobblestone});
      GameRegistry.addRecipe(new ItemStack(KetherStonePillarBase, 1), new Object[]{" Y ", " Y ", "YYY", 'Y', KetherCobblestone});
      GameRegistry.addRecipe(new ItemStack(FullCloth, 1), new Object[]{"YYY", "YYY", "YYY", 'Y', APieceOfCloth});
      GameRegistry.addRecipe(new ItemStack(KetherRedStoneBrick, 1), new Object[]{"Y", "X", 'Y', KetherStoneBrick, 'X', RedFlowerEssence});
      GameRegistry.addRecipe(new ItemStack(KetherBlueStoneBrick, 1), new Object[]{"Y", "X", 'Y', KetherStoneBrick, 'X', BlueFlowerEssence});
      GameRegistry.addRecipe(new ItemStack(KetherYellowStoneBrick, 1), new Object[]{"Y", "X", 'Y', KetherStoneBrick, 'X', YellowFlowerEssence});
      GameRegistry.addRecipe(new ItemStack(KetherStoneSquare, 4), new Object[]{"YYY", "Y Y", "YYY", 'Y', KetherStone});
      GameRegistry.addRecipe(new ItemStack(KetherStonePanel, 6), new Object[]{"YYY", "YYY", "YYY", 'Y', KetherStone});
      GameRegistry.addRecipe(new ItemStack(KetherStoneBrick, 4), new Object[]{"YY", "YY", 'Y', KetherStone});
      GameRegistry.addRecipe(new ItemStack(DemonEyeSummoner, 1), new Object[]{"###", "YYY", "XXX", '#', YellowFlowerEssence, 'Y', BlueFlowerEssence, 'X', RedFlowerEssence});
      GameRegistry.addRecipe(new ItemStack(KetherPlanks, 4), new Object[]{"#", '#', KetherLog});
      GameRegistry.addRecipe(new ItemStack(Joint, 1), new Object[]{"###", "#XX", "###", '#', Items.paper, 'X', Weed});
      GameRegistry.addRecipe(new ItemStack(KetherPortalLighter, 1), new Object[]{"X ", " Y", 'X', MagicStone, 'Y', Items.flint});
      (new RecipesKetherTools()).addRecipes();
      (new RecipesKetherWeapons()).addRecipes();
      (new RecipesKetherArmor()).addRecipes();
      (new RecipesKetherGemBlocks()).addRecipes();
      (new RecipesRevertedKetherGemBlocks()).addRecipes();
      GameRegistry.addSmelting(RubyOre, new ItemStack(RubyGem, 1), 1.0F);
      GameRegistry.addSmelting(TopazOre, new ItemStack(TopazGem, 1), 1.0F);
      GameRegistry.addSmelting(SapphireOre, new ItemStack(SapphireGem, 1), 1.0F);
      GameRegistry.addSmelting(LonsdaleiteOre, new ItemStack(LonsdaleiteGem, 1), 2.0F);
      GameRegistry.addSmelting(Crystals, new ItemStack(KetherEnergy, 3), 5.0F);
      GameRegistry.addSmelting(KetherStoneBrick, new ItemStack(KetherEnchantedStoneBrick, 1), 1.0F);
      GameRegistry.addSmelting(KetherCobblestone, new ItemStack(KetherStone, 1), 0.0F);
      GameRegistry.addSmelting(AdamantiumOre, new ItemStack(AdamantiumIngot, 1), 15.0F);
      DimensionManager.registerProviderType(8, WorldProviderKether.class, false);
      DimensionManager.registerDimension(8, 8);
      GameRegistry.registerWorldGenerator(this.eventmanager1, 0);
      GameRegistry.registerWorldGenerator(this.eventmanager2, 0);
      serverSide.registerRenderThings();
      this.addNames();
   }

   @EventHandler
   public void postInit(FMLPostInitializationEvent event) {
      serverSide.addNamesToClient();
   }

   public static int getUniqueEntityId() {
      do {
         ++startEntityId;
      } while(EntityList.getStringFromID(startEntityId) != null);

      return startEntityId;
   }

   public static void registerEntityEgg(Class entity, int primaryColor, int secondaryColor) {
      int id = getUniqueEntityId();
      EntityList.IDtoClassMapping.put(id, entity);
      EntityList.entityEggs.put(id, new EntityEggInfo(id, primaryColor, secondaryColor));
   }

   public void addNames() {
      LanguageRegistry.addName(KetherDirt, "Kether Dirt");
      LanguageRegistry.addName(KetherGrass, "Kether Grass");
      LanguageRegistry.addName(KetherPortal, "Kether Portal");
      LanguageRegistry.addName(MagicStone, "Magic Stone");
      LanguageRegistry.addName(KetherPortalLighter, "Kether Portal Lighter");
      LanguageRegistry.addName(KetherCloud, "Kether Cloud");
      LanguageRegistry.addName(KetherLeaves, "Kether Leaves");
      LanguageRegistry.addName(KetherLog, "Kether Log");
      LanguageRegistry.addName(KetherPlanks, "Kether Planks");
      LanguageRegistry.addName(KetherTallGrass, "Kether Tall Grass");
      LanguageRegistry.addName(SapphireOre, "Sapphire Ore");
      LanguageRegistry.addName(SapphireGem, "Sapphire Gem");
      LanguageRegistry.addName(TopazGem, "Topaz Gem");
      LanguageRegistry.addName(RubyGem, "Ruby Gem");
      LanguageRegistry.addName(LonsdaleiteGem, "Lonsdaleite Gem");
      LanguageRegistry.addName(TopazOre, "Topaz Ore");
      LanguageRegistry.addName(RubyOre, "Ruby Ore");
      LanguageRegistry.addName(LonsdaleiteOre, "Lonsdaleite Ore");
      LanguageRegistry.addName(SapphirePickaxe, "Sapphire Pickaxe");
      LanguageRegistry.addName(SapphireAxe, "Sapphire Axe");
      LanguageRegistry.addName(SapphireHoe, "Sapphire Hoe");
      LanguageRegistry.addName(SapphireShovel, "Sapphire Shovel");
      LanguageRegistry.addName(SapphireSword, "Sapphire Sword");
      LanguageRegistry.addName(RubyPickaxe, "Ruby Pickaxe");
      LanguageRegistry.addName(RubyAxe, "Ruby Axe");
      LanguageRegistry.addName(RubyHoe, "Ruby Hoe");
      LanguageRegistry.addName(RubyShovel, "Ruby Shovel");
      LanguageRegistry.addName(RubySword, "Ruby Sword");
      LanguageRegistry.addName(TopazPickaxe, "Topaz Pickaxe");
      LanguageRegistry.addName(TopazAxe, "Topaz Axe");
      LanguageRegistry.addName(TopazHoe, "Topaz Hoe");
      LanguageRegistry.addName(TopazShovel, "Topaz Shovel");
      LanguageRegistry.addName(TopazSword, "Topaz Sword");
      LanguageRegistry.addName(LonsdaleitePickaxe, "Lonsdaleite Pickaxe");
      LanguageRegistry.addName(LonsdaleiteAxe, "Lonsdaleite Axe");
      LanguageRegistry.addName(LonsdaleiteHoe, "Lonsdaleite Hoe");
      LanguageRegistry.addName(LonsdaleiteShovel, "Lonsdaleite Shovel");
      LanguageRegistry.addName(LonsdaleiteSword, "Lonsdaleite Sword");
      LanguageRegistry.addName(Weed, "Weed");
      LanguageRegistry.addName(Hemp, "Hemp");
      LanguageRegistry.addName(Joint, "Joint");
      LanguageRegistry.addName(SapphireBoots, "Sapphire Boots");
      LanguageRegistry.addName(SapphireLeggins, "Sapphire Leggins");
      LanguageRegistry.addName(SapphireChestplate, "Sapphire Chestplate");
      LanguageRegistry.addName(SapphireHelmet, "Sapphire Helmet");
      LanguageRegistry.addName(TopazBoots, "Topaz Boots");
      LanguageRegistry.addName(TopazLeggins, "Topaz Leggins");
      LanguageRegistry.addName(TopazChestplate, "Topaz Chestplate");
      LanguageRegistry.addName(TopazHelmet, "Topaz Helmet");
      LanguageRegistry.addName(RubyBoots, "Ruby Boots");
      LanguageRegistry.addName(RubyLeggins, "Ruby Leggins");
      LanguageRegistry.addName(RubyChestplate, "Ruby Chestplate");
      LanguageRegistry.addName(RubyHelmet, "Ruby Helmet");
      LanguageRegistry.addName(LonsdaleiteBoots, "§bLonsdaleite Boots");
      LanguageRegistry.addName(LonsdaleiteLeggins, "§bLonsdaleite Leggins");
      LanguageRegistry.addName(LonsdaleiteChestplate, "§bLonsdaleite Chestplate");
      LanguageRegistry.addName(LonsdaleiteHelmet, "§bLonsdaleite Helmet");
      LanguageRegistry.addName(KetherLonsdaleiteLeaves, "Kether Lonsdaleite Leaves");
      LanguageRegistry.addName(KetherLonsdaleiteLog, "Kether Lonsdaleite Log");
      LanguageRegistry.addName(KetherYellowFlower, "Kether Yellow Flower");
      LanguageRegistry.addName(YellowFlowerEssence, "Yellow Flower Essence");
      LanguageRegistry.addName(BlueFlowerEssence, "Blue Flower Essence");
      LanguageRegistry.addName(KetherBlueFlower, "Kether Blue Flower");
      LanguageRegistry.addName(RedFlowerEssence, "Red Flower Essence");
      LanguageRegistry.addName(KetherRedFlower, "Kether Red Flower");
      LanguageRegistry.addName(JumpBoots, "§fJump Boots");
      LanguageRegistry.addName(KetherSapling, "Kether Sapling");
      LanguageRegistry.addName(KetherBlueWand, "Kether Blue Wand");
      LanguageRegistry.addName(KetherRedWand, "Kether Red Wand");
      LanguageRegistry.addName(KetherYellowWand, "Kether Yellow Wand");
      LanguageRegistry.addName(SapphireBlock, "Sapphire Block");
      LanguageRegistry.addName(TopazBlock, "Topaz Block");
      LanguageRegistry.addName(RubyBlock, "Ruby Block");
      LanguageRegistry.addName(LonsdaleiteBlock, "Lonsdaleite Block");
      LanguageRegistry.addName(KetherWand, "§bKether Wand");
      LanguageRegistry.addName(KetherEnergy, "§bKether Energy");
      LanguageRegistry.addName(Mycena, "Mycena");
      LanguageRegistry.addName(Crystals, "§bCrystals");
      LanguageRegistry.addName(HermesBoots, "ďż˝eHermes Boots");
      LanguageRegistry.addName(DarkEnergy, "Dark Energy");
      LanguageRegistry.addName(BlueFruit, "Blue Fruit");
      LanguageRegistry.addName(KetherStatue, "Kether Statue");
      LanguageRegistry.addName(DemonEyeSummoner, "Demon Eye Summoner");
      LanguageRegistry.addName(KetherKey, "§bKether Key");
      LanguageRegistry.addName(Pytajnik, "§3???");
      LanguageRegistry.addName(KetherStone, "Kether Stone");
      LanguageRegistry.addName(ScrableStone, "Scrable Stone");
      LanguageRegistry.addName(ScrapyStone, "Scrapy Stone");
      LanguageRegistry.addName(ScrapyBrick, "Scrapy Brick");
      LanguageRegistry.addName(CarvedScrapyBrick, "Carved Scrapy Brick");
      LanguageRegistry.addName(UnbreakbleKetherLog, "Unbreakble Kether Log");
      LanguageRegistry.addName(UnbreakbleKetherLeaves, "Unbreakble Kether Leaves");
      LanguageRegistry.addName(KetherStoneBrick, "Kether Stone Brick");
      LanguageRegistry.addName(KetherRedStoneBrick, "Kether Red Stone Brick");
      LanguageRegistry.addName(KetherYellowStoneBrick, "Kether Yellow Stone Brick");
      LanguageRegistry.addName(KetherBlueStoneBrick, "Kether Blue Stone Brick");
      LanguageRegistry.addName(LegendaryMagicWand, "Legendary Magic Wand");
      LanguageRegistry.addName(KetherGlowBrick, "Kether Glow Brick");
      LanguageRegistry.addName(KetherMossyStone, "Kether Mossy Stone");
      LanguageRegistry.addName(KetherEnchantedStoneBrick, "Kether Enchanted Stone Brick");
      LanguageRegistry.addName(KetherStoneSquare, "Kether Stone Square");
      LanguageRegistry.addName(KetherStonePanel, "Kether Stone Panel");
      LanguageRegistry.addName(KetherCobblestone, "Kether Cobblestone");
      LanguageRegistry.addName(HealingFlower, "Healing Flower");
      LanguageRegistry.addName(KetherCrocodileLeather, "Kether Crocodile Leather");
      LanguageRegistry.addName(KetherCrocodileTooth, "Kether Crocodile Tooth");
      LanguageRegistry.addName(APieceOfCloth, "A Piece Of Cloth");
      LanguageRegistry.addName(FullCloth, "Full Cloth");
      LanguageRegistry.instance().addStringLocalization("itemGroup.Kether Tab", "Kether Tab");
      LanguageRegistry.addName(KetherStonePillarBase, "Kether Stone Pillar Base");
      LanguageRegistry.addName(KetherStonePillarCenter, "Kether Stone Pillar Center");
      LanguageRegistry.addName(KetherStonePillarTop, "Kether Stone Pillar Top");
      LanguageRegistry.addName(KetherBlueLeaves, "Kether Blue Leaves");
      LanguageRegistry.addName(KetherYellowStoneBrickPillarBase, "Kether Yellow Stone Brick Pillar Base");
      LanguageRegistry.addName(KetherYellowStoneBrickPillarCenter, "Kether Yellow Stone Brick Pillar Center");
      LanguageRegistry.addName(KetherYellowStoneBrickPillarTop, "Kether Yellow Stone Brick Pillar Top");
      LanguageRegistry.addName(GravityWand, "Gravity Wand");
      LanguageRegistry.addName(KetherBlackRose, "Kether Black Rose");
      LanguageRegistry.addName(KetherBlueRose, "Kether Blue Rose");
      LanguageRegistry.addName(KetherPurpleRose, "Kether Purple Rose");
      LanguageRegistry.addName(KetherLightBlueRose, "Kether Light Blue Rose");
      LanguageRegistry.addName(LifeLeaves, "Life Leaves");
      LanguageRegistry.addName(LifeLog, "Life Log");
      LanguageRegistry.addName(SmallWings, "Small Wings");
      LanguageRegistry.addName(Wings, "Wings");
      LanguageRegistry.addName(EnergyCrystal, "§bEnergy Crystal");
      LanguageRegistry.addName(EnergyConverter, "Energy Converter");
      LanguageRegistry.addName(EnergyConverterActive, "Energy Converter");
      LanguageRegistry.addName(GiftsBlock, "Don't use that!");
      LanguageRegistry.addName(EnergyEnchanter, "Energy Enchanter");
      LanguageRegistry.addName(EnergyEnchanterActive, "Energy Enchanter");
      LanguageRegistry.addName(MalachiteOre, "Malachite Ore");
      LanguageRegistry.addName(Malachite, "Malachite");
      LanguageRegistry.addName(MalachiteBlock, "Malachite Block");
      LanguageRegistry.addName(MalachiteTiles, "Malachite Tiles");
      LanguageRegistry.addName(CloudDust, "Cloud Dust");
      LanguageRegistry.addName(CottonCandy, "Cotton Candy");
      LanguageRegistry.addName(AdamantiumOre, "Adamantium Ore");
      LanguageRegistry.addName(AdamantiumBlock, "Adamantium Block");
      LanguageRegistry.addName(AdamantiumIngot, "Adamantium Ingot");
      LanguageRegistry.addName(AdamantiumBoots, "Adamantium Boots");
      LanguageRegistry.addName(AdamantiumLeggins, "Adamantium Leggins");
      LanguageRegistry.addName(AdamantiumChestplate, "Adamantium Chestplate");
      LanguageRegistry.addName(AdamantiumHelmet, "Adamantium Helmet");
      LanguageRegistry.addName(AdamantiumPickaxe, "Adamantium Pickaxe");
      LanguageRegistry.addName(AdamantiumAxe, "Adamantium Axe");
      LanguageRegistry.addName(AdamantiumHoe, "Adamantium Hoe");
      LanguageRegistry.addName(AdamantiumShovel, "Adamantium Shovel");
      LanguageRegistry.addName(AdamantiumSword, "Adamantium Sword");
      LanguageRegistry.addName(KetherMagicFlower, "Kether Magic Flower");
      LanguageRegistry.addName(ShadowOre, "Shadow Ore");
      LanguageRegistry.addName(ShadowBlock, "Shadow Block");
      LanguageRegistry.addName(ShadowGem, "Shadow Gem");
      LanguageRegistry.addName(ShadowBoots, "Shadow Boots");
      LanguageRegistry.addName(ShadowLeggins, "Shadow Leggins");
      LanguageRegistry.addName(ShadowChestplate, "Shadow Chestplate");
      LanguageRegistry.addName(ShadowHelmet, "Shadow Helmet");
      LanguageRegistry.addName(ShadowPickaxe, "Shadow Pickaxe");
      LanguageRegistry.addName(ShadowAxe, "Shadow Axe");
      LanguageRegistry.addName(ShadowHoe, "Shadow Hoe");
      LanguageRegistry.addName(ShadowShovel, "Shadow Shovel");
      LanguageRegistry.addName(ShadowSword, "Shadow Sword");
      LanguageRegistry.addName(SaintOre, "Saint Ore");
      LanguageRegistry.addName(SaintBlock, "Saint Block");
      LanguageRegistry.addName(SaintGem, "Saint Gem");
      LanguageRegistry.addName(SaintBoots, "Saint Boots");
      LanguageRegistry.addName(SaintLeggins, "Saint Leggins");
      LanguageRegistry.addName(SaintChestplate, "Saint Chestplate");
      LanguageRegistry.addName(SaintHelmet, "Saint Helmet");
      LanguageRegistry.addName(SaintPickaxe, "Saint Pickaxe");
      LanguageRegistry.addName(SaintAxe, "Saint Axe");
      LanguageRegistry.addName(SaintHoe, "Saint Hoe");
      LanguageRegistry.addName(SaintShovel, "Saint Shovel");
      LanguageRegistry.addName(SaintSword, "Saint Sword");
      LanguageRegistry.addName(GlowingKetherGrass, "Glowing Kether Grass");
      LanguageRegistry.addName(KetherGoldenLeaves, "Kether Golden Leaves");
      LanguageRegistry.addName(MidasHand, "Midas Hand");
      LanguageRegistry.addName(MagicFruit, "Magic Fruit");
      LanguageRegistry.addName(MovingSands, "Moving Sands");
      LanguageRegistry.addName(LameMeat, "Lame Meat");
      LanguageRegistry.addName(Venison, "Venison");
   }
}
